### ISSUE TITLE
[Feature] Allow keywords and hotkeys to be setup with new User Configurations  

### ISSUE THREAD

**Issue by willdhorn** [mr-pennyworth/alfred-better-dictionaries#16]
Alfred 5 added [User Configurations](https://www.alfredapp.com/help/workflows/user-configuration/) to workflows to allow for easier setup of imported workflows. It would be especially helpful to be able to setup keywords and hotkeys for this workflow using user configurations.

**Comment by mr-pennyworth** [comment]
That's an interesting idea @willdhorn!

I personally find Alfred's visual workflow editor helpful and intuitive.
Since keywords and hotkeys can be set in the UI, this feature for me falls in
the category of "could be a nice-to-have, but don't personally see a lot of value"
<img width="1032" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/74945464/89d8131a-0de2-4d76-a462-ad2b50883500">

I'll move ahead and close this as "not planned", but of course,
if someone sends a patch, I'd be happy to merge 😇
