### ISSUE TITLE
No such xattr: com.apple.quarantine

### ISSUE THREAD

**Issue by saeedesmaili** [mr-pennyworth/alfred-better-dictionaries#26]
When running `.setup-better-dictionaries` I get the following error:

![image](https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/13351748/7d5afa73-049a-43ee-88cd-9558366b9c68)

I've installed the latest version of the workflow, and I'm using alfred 5.5 [2257]

**Comment by White-White** [comment]
same error here

**Comment by makzsslm** [comment]
same here.

when trying to run .dict-import I get the following error:


<img width="1017" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/125161526/ddcfd28d-825f-40a3-81eb-35c8520dfc7e">


any news on this ?

**Comment by mr-pennyworth** [comment]
Thanks @saeedesmaili and @White-White for reporting the error messages!
These error messages actually don't matter. I have silenced these error messages now: e8ff037c24d97655436c27ff62d6d293815ebaae 

@makzsslm, I have identified the issue and fixed it: 6cf3c2aefcc4daee72d0b8c9a6a512c1addd9c77

Both of the issues should now be fixed in the latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.9
