### ISSUE TITLE
Dict entries are not very readable (too transparent/use of grey colour on characters)

### ISSUE THREAD

**Issue by deafmute1** [mr-pennyworth/alfred-better-dictionaries#32]
Dict entries are more transparent than the theme itself combined with the use of light coloured lettering and a light background makes it very hard to read. 

In README.md pictures it shows the extra pane following alfred's theming settings but no matter what theme I select it seems to be identical?

**Comment by mr-pennyworth** [comment]
Thanks for the report @deafmute1!
See https://github.com/mr-pennyworth/alfred-extra-pane/issues/14 for background.
Make sure that you have the latest version of the workflow https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.15

To determine whether you have the same issue,
1. switch to a theme that doesn't use any transparency or blur
2. kill all processes named `AlfredExtraPane`
3. look up something in the dictionary and see if the problem is resolved

To kill the process,
<img width="958" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/74945464/62944a95-72c8-431e-a038-847c6768c182">
0. Open Activity Monitor
1. Search for "AlfredExtraPane"
2. Double click on the result
3. Click "quit"

**Comment by deafmute1** [comment]
Restarting AlfredExtraPane.app, after upgrading the version of it in /Applications to the latest version fixed it for me. As I had installed AlfredExtraPane.app for another workflow manually before, updating the workflow itself didn't work.
