### ISSUE TITLE
Feature Request: Import non-default dictinaries

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-better-dictionaries#7]
It would be great, if your workflow could somehow import more dictionaries than the Mac OS Default ones. I have installed a dictionary to translate german-english in the Dictionary.app for example, but it isn't shown in the list of importable dictionaries for BetterDict.

**Comment by mr-pennyworth** [comment]
Thanks @chrisgrieser for the feature request!

Would it be possible for you to see if the German dictionary shows up with the latest build?
https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.6
(Tested on Intel Mac only, help in testing on Apple Silicon greatly appreciated 😇)

I imported Oxford German Dictionary in `Dictionary.app` and it does show up when I type `.dict-import` in Alfred.

**Comment by chrisgrieser** [comment]
I am on an M1 mac, and the workflow itself works.The Oxford Germany Dictionary indeed works, though it is a builtin one for me.

One I'd like to use would be [Terminology](https://agiletortoise.com/terminology/mac/), but that one does not show up as import option :/

**Comment by mr-pennyworth** [comment]
@chrisgrieser fixed in  https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.7


There are still issues in parsing the dictionary correctly, so the previews don't look as nice as other dictionaries, but it is usable. I won't be able to spend time on debugging at the moment, but will gladly merge patches to fix the parsing :)

See 3be9a6c if you're curious about what exactly was broken and the fix 😇
